// Dashboard Pages
export { default as DashboardPage } from './DashboardPage'
export { default as FileUploadPage } from './FileUploadPage'
export { default as LoginHistory } from './LoginHistory'
export { default as ProfitLoss } from './ProfitLoss'
export { default as IntradayHistory } from './IntradayHistory'
export { default as RunSettlement } from './RunSettlement'
export { default as ScriptBufferLimit } from './ScriptBufferLimit'
export { default as ScriptMaster } from './ScriptMaster'
export { default as TradeMarginPage } from './TradeMarginPage'
export { default as WeeklyAdmin } from './WeeklyAdmin'
export { default as M2MReport } from './M2MReport'